name: tfm
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - requests
  - openpyxl
  - seaborn
  - scikit-learn
  - statsmodels
  - keras